const types = {
    // Socket
    SOCKET_SUCCESS: 'SOCKET_SUCCESS',
    SOCKET_JOIN_GAME: 'SOCKET_JOIN_GAME',
    SOCKET_REGISTER_LISTENER: 'SOCKET_REGISTER_LISTENER',
    SOCKET_START_GAME: 'SOCKET_START_GAME',
    SOCKET_UPDATE_SCORE: 'SOCKET_UPDATE_SCORE',
    PLAYER_UPDATE_SCORE: 'PLAYER_UPDATE_SCORE',
    ADD_PLAYER: 'ADD_PLAYER'
};

export default types;
