const types = {
    // Socket
    SOCKET_SUCCESS: 'SOCKET_SUCCESS',
    SOCKET_JOIN_GAME: 'SOCKET_JOIN_GAME',
    SOCKET_REGISTER_LISTENER: 'SOCKET_REGISTER_LISTENER',
    SOCKET_START_GAME: 'SOCKET_START_GAME'
};

export default types;
